### ISSUE TITLE
Support repository labels

### ISSUE THREAD

**Issue by bjencks** [chainguard-dev/rules_apko#82]
apko supports @labels on repositories and generates a proper lockfile, but then rules_apko fails with an error like `Error in download: java.io.IOException: Bad URL: @testing https://dl-cdn.alpinelinux.org/alpine/edge/testing/aarch64/APKINDEX.tar.gz`

```
contents:
  repositories:
    - https://dl-cdn.alpinelinux.org/alpine/v3.20/main
    - "@testing https://dl-cdn.alpinelinux.org/alpine/edge/testing"
  packages:
    - alpine-base
    - tayga@testing
```
